"""
app/models/domain.py
─────────────────────
Internal domain types used throughout the application.
These are NOT the API response types (see responses.py for those).
These are the internal plumbing types passed between layers.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class BoundingBox:
    """
    A geographic bounding box in WGS84 (EPSG:4326) coordinates.
    Used to define the analysis area submitted by the user.

    All coordinates are decimal degrees:
        lat = latitude  (north-south), range: -90 to +90
        lng = longitude (east-west),   range: -180 to +180

    Example — Research Triangle area of North Carolina:
        BoundingBox(min_lat=35.7, min_lng=-79.2, max_lat=36.2, max_lng=-78.6)
    """
    min_lat: float
    min_lng: float
    max_lat: float
    max_lng: float

    def center(self) -> tuple[float, float]:
        """Returns (lat, lng) of the center point."""
        return (
            (self.min_lat + self.max_lat) / 2,
            (self.min_lng + self.max_lng) / 2,
        )

    def area_sq_km(self) -> float:
        """
        Approximate area in square kilometers.
        Uses the equirectangular approximation — accurate enough for scoring.
        1 degree latitude ≈ 111 km everywhere.
        1 degree longitude ≈ 111 km * cos(latitude) at the given latitude.
        """
        import math
        lat_km = (self.max_lat - self.min_lat) * 111.0
        lng_km = (self.max_lng - self.min_lng) * 111.0 * math.cos(math.radians(self.center()[0]))
        return abs(lat_km * lng_km)

    def to_geojson_polygon(self) -> dict:
        """Convert to a GeoJSON Polygon dict (exterior ring only)."""
        return {
            "type": "Polygon",
            "coordinates": [[
                [self.min_lng, self.min_lat],
                [self.max_lng, self.min_lat],
                [self.max_lng, self.max_lat],
                [self.min_lng, self.max_lat],
                [self.min_lng, self.min_lat],  # close the ring
            ]]
        }

    def overpass_bbox(self) -> str:
        """Format for Overpass API: 'south,west,north,east'"""
        return f"{self.min_lat},{self.min_lng},{self.max_lat},{self.max_lng}"


@dataclass
class GridCell:
    """
    One candidate location within the analysis bounding box.
    Generated by app/core/grid.py at the requested grid resolution.

    Each cell is a square region centered on (lat, lng).
    The cell_polygon defines the exact boundary.
    """
    lat: float
    lng: float
    cell_size_km: float
    cell_polygon: dict  # GeoJSON Polygon


@dataclass
class CellScore:
    """
    The scoring result for a single grid cell, from a single scorer.
    Scorers produce one CellScore per grid cell.
    The engine merges all CellScores across all scorers into ScoreBundles.

    raw_scores: dict mapping category_id → float (0.0–1.0)
                Only ONE key will be set by each scorer (its own category).
                Example from PowerScorer: {"power": 0.83}

    metrics: dict of raw metric values — the underlying data before scoring.
             Used to populate the ScoreMetrics response object.
             Keys match the metric field names in the relevant *Metrics model.

    sub_scores: dict mapping sub-metric name → float (0.0–1.0)
                The individual component scores before rolling up to the
                category score. Useful for debugging and display.

    error: if not None, this scorer failed for this cell. Score should be
           treated as None (excluded from composite) and this message logged.
    """
    lat: float
    lng: float
    raw_scores: dict[str, float] = field(default_factory=dict)
    metrics: dict = field(default_factory=dict)
    sub_scores: dict[str, float] = field(default_factory=dict)
    error: Optional[str] = None


@dataclass
class IntegrationError(Exception):
    """
    Raised by integration clients when a data source call fails.
    Always caught at the scorer level — never allowed to reach the API.

    source: the integration that failed (e.g. "eia", "fema", "osm")
    message: human-readable description of what went wrong
    status_code: HTTP status code if applicable
    """
    source: str
    message: str
    status_code: Optional[int] = None

    def __str__(self):
        return f"IntegrationError({self.source}): {self.message}"
